#!/usr/bin/env bash
# Opens an archive in nsxiv.

if [ "$1" = "" ]; then
    echo "Usage: $0 <archive>" >&2
    exit 1
fi

CB_FILE="$1"

mnt="$(mktemp -d "${TMPDIR:-/tmp}/nsxiv-cb-archive-XXX")"

fuse-archive "$CB_FILE" "$mnt" -o auto_unmount

cleanup () {
    fusermount -u "$mnt"
    rmdir "$mnt"
}
trap cleanup EXIT

CB_FILE_DIRNAME="$(dirname "$CB_FILE")"
CB_FILE_BASE="$(basename "$CB_FILE")"
CB_FILE_BASE_HASH="$(printf "%s" "$CB_FILE_BASE" | md5sum | cut -d ' ' -f 1)"
NSXIV_SHARE_PATH="$HOME/.local/share/nsxiv"
NSXIV_SESSION_PATH="${NSXIV_SHARE_PATH}/session"
NSXIV_SESSION_FILE="${NSXIV_SESSION_PATH}/${CB_FILE_BASE_HASH}.tsv"

if [ -e "$NSXIV_SESSION_FILE" ]; then
    NSXIV_SESSION_FILE_INDEX="$(cut -f1 "$NSXIV_SESSION_FILE")"
else
    NSXIV_SESSION_FILE_INDEX=1
fi

EXIT_OUTPUT="$(nsxiv -a -b -p -s w -q -r -C -n"$NSXIV_SESSION_FILE_INDEX" "$mnt")"

EXIT_FILE_INDEX="$(echo "$EXIT_OUTPUT" | cut -f1)"
EXIT_FILE_COUNT="$(echo "$EXIT_OUTPUT" | cut -f2)"
EXIT_FILE_NAME="$(echo "$EXIT_OUTPUT" | cut -f3)"
EXIT_FILE_NAME="$(basename "$EXIT_FILE_NAME")"

if [ -n "$EXIT_FILE_NAME" ]; then
    if  [ "$EXIT_FILE_INDEX" == "1" ] ||
        [ "$EXIT_FILE_INDEX" == "$EXIT_FILE_COUNT" ];
    then
        rm -f "$NSXIV_SESSION_FILE"
    elif [ "$EXIT_FILE_INDEX" != "$NSXIV_SESSION_FILE_INDEX" ]; then
        printf '%s\t%s\t%s\t%s\t%s' "$EXIT_FILE_INDEX" "$EXIT_FILE_COUNT" \
            "$EXIT_FILE_NAME" "$CB_FILE_BASE" "$CB_FILE_DIRNAME" >"$NSXIV_SESSION_FILE"
    fi
else
    echo "Unknown error, not saving." >&2
fi
