#!/bin/sh

tmpfile="${TMPDIR:-/tmp}/nsxiv_pipe_$$"
trap 'rm -f -- "$tmpfile"' EXIT TERM INT QUIT

if ! [ -t 0 ]; then
    # drain stdin to tmpfile if it's not connected to a terminal
    cat > "$tmpfile" || { echo "draining stdin failed" >&2; exit 1; }
fi

if [ -s "$tmpfile" ]; then
    nsxiv "$tmpfile" "$@"
else  # fallback
    [ "$#" -eq 0 ] && {
        cat >&2 << EOF
nsxiv-pipe: Error: no file or stdin provided
Usage:
  nsxiv-pipe < /path/to/file
  curl "\$image_url" | nsxiv-pipe
EOF
        exit 1;
    }
    nsxiv "$@"
fi
