From 0e8bc7a6d224c0a30564eb9e5a9df716b1936238 Mon Sep 17 00:00:00 2001
From: Jakob <jakob@knugen.nu>
Date: Wed, 26 Jun 2024 07:16:55 +0200
Subject: [PATCH] Include appstream metadata

---
 Makefile                                   | 14 ++++++++++--
 1 file changed, 12 insertions(+), 2 deletions(-)

diff --git a/Makefile b/Makefile
index b7ee37b..4ed8507 100644
--- a/Makefile
+++ b/Makefile
@@ -55,7 +55,7 @@ dump_cppflags:
 clean:
 	rm -f *.o nsxiv version.h
 
-install-all: install install-desktop install-icon
+install-all: install install-desktop install-icon install-metainfo
 
 install-desktop:
 	@echo "INSTALL nsxiv.desktop"
@@ -78,6 +78,16 @@ uninstall-icon:
 		rm -f "$$dir/nsxiv.png"; \
 	done
 
+install-metainfo:
+	@echo "INSTALL page.codeberg.nsxiv.nsxiv.metainfo.xml"
+	mkdir -p $(DESTDIR)$(PREFIX)/share/metainfo
+	cp etc/page.codeberg.nsxiv.nsxiv.metainfo.xml $(DESTDIR)$(PREFIX)/share/metainfo
+	chmod 644 $(DESTDIR)$(PREFIX)/share/metainfo/page.codeberg.nsxiv.nsxiv.metainfo.xml
+
+uninstall-metainfo:
+	@echo "REMOVE page.codeberg.nsxiv.nsxiv.metainfo.xml"
+	rm -f $(DESTDIR)$(PREFIX)/share/metainfo/page.codeberg.nsxiv.nsxiv.metainfo.xml
+
 install: all
 	@echo "INSTALL bin/nsxiv"
 	mkdir -p $(DESTDIR)$(PREFIX)/bin
@@ -93,7 +103,7 @@ install: all
 	cp etc/examples/* $(DESTDIR)$(EGPREFIX)
 	chmod 755 $(DESTDIR)$(EGPREFIX)/*
 
-uninstall: uninstall-icon
+uninstall: uninstall-icon uninstall-metainfo
 	@echo "REMOVE bin/nsxiv"
 	rm -f $(DESTDIR)$(PREFIX)/bin/nsxiv
 	@echo "REMOVE nsxiv.1"
-- 
2.39.2

