#!/usr/bin/env sh
# Opens an archive in nsxiv.

if [ "$1" = "" ]; then
    echo "Usage: $0 <archive>" >&2
    exit 1
fi

cb_file="$1"

mnt="$(mktemp -d "${TMPDIR:-/tmp}/nsxiv-cb-archive-XXX")"

fuse-archive "$cb_file" "$mnt" -o auto_unmount

cleanup () {
    fusermount -u "$mnt"
    rmdir "$mnt"
}
trap cleanup EXIT

cb_file_dirname="$(dirname "$cb_file")"
cb_file_base="$(basename "$cb_file")"
cb_file_hash="$(printf "%s" "$cb_file_base" | md5sum | cut -d ' ' -f 1)"
nsxiv_session_path="${XDG_DATA_HOME:-$HOME/.local/share}/nsxiv-cb"
mkdir -p "$nsxiv_session_path" || { echo "failed to make directory" >&2; exit 1; }
nsxiv_session_file="${nsxiv_session_path}/${cb_file_hash}.tsv"

if [ -e "$nsxiv_session_file" ]; then
    file_index="$(cut -f1 "$nsxiv_session_file")"
else
    file_index=1
fi

exit_output="$(nsxiv -a -b -p -s w -q -r -C -n"$file_index" "$mnt")"

exit_file_index="$(echo "$exit_output" | cut -f1)"
exit_file_count="$(echo "$exit_output" | cut -f2)"
exit_file_name="$(echo "$exit_output" | cut -f3)"
exit_file_name="$(basename "$exit_file_name")"

if [ -n "$exit_file_name" ]; then
    if  [ "$exit_file_index" = "1" ] ||
        [ "$exit_file_index" = "$exit_file_count" ];
    then
        rm -f "$nsxiv_session_file"
    elif [ "$exit_file_index" != "$file_index" ]; then
        printf '%s\t%s\t%s\t%s\t%s' "$exit_file_index" "$exit_file_count" \
            "$exit_file_name" "$cb_file_base" "$cb_file_dirname" >"$nsxiv_session_file"
    fi
else
    echo "Unknown error, not saving." >&2
fi
