#!/bin/sh

# set these to your monitor resolution or something like that
maxw=720
maxh=720

[ -z "$1" ] && { echo "Usage: nsxiv-fill image" >&2; exit 1; }

dim="$(imlib2_load -vvj "$1" | grep -o -E 'WxH=([[:digit:]]+x[[:digit:]]+)')"
dim="${dim#WxH=}"
w="${dim%%x*}"
h="${dim##*x}"

if ! [ "$w" -eq "$w" ] 2>/dev/null || ! [ "$h" -eq "$h" ] 2>/dev/null; then
	echo "Couldn't load the file" >&2
	exit 1
fi

if [ "$w" -gt "$maxw" ]; then
	h=$(( (maxw * h) / w ))
	w=$maxw
fi

if [ "$h" -gt "$maxh" ]; then
	w=$(( (maxh * w) / h ))
	h=$maxh
fi

nsxiv -b -N "nsxiv-fill" -g "${w}x${h}" "$1"
