#!/bin/sh

delay=1
images="$HOME/Pictures"
geometry="$(xdpyinfo | grep 'dimensions:' | cut -d' ' -f7)"

nsxiv -bf -r -S "$delay" -e "$XSCREENSAVER_WINDOW" -g "$geometry" -s F "$images"
#         ^ remove if you don't want images from the sub-directories
