#!/usr/bin/env sh

set -e

[ -z "$OPENER" ] && OPENER="xdg-open" # OPENER is `eval`ed
[ -z "$CACHEDIR" ] && CACHEDIR="${NSXIV_THUMB_CACHE_DIR:-"${XDG_CACHE_HOME:-"$HOME/.cache"}/nsxiv-extra/nsxiv-thumb"}"
# extension of thumbnails. can be jpg or png.
[ -z "$EXT" ] && EXT="jpg"
# maximum number of processes. 0 is as many as your system can handle.
[ -z "$MAXPROCS" ] && MAXPROCS="${NSXIV_THUMB_MAX_PROCS:-"$(($(nproc) * 4))"}"
[ -z "$SIZE" ] && SIZE=384
[ -z "$NSXIV_EXEC" ] && NSXIV_EXEC="nsxiv"

export CACHEDIR
export EXT
export SIZE

mkdir -p -- "$CACHEDIR"
tmpdir="$(mktemp -d)" || {
    printf "%s: %s\n" "${0##*/}" "could not create temporary directory"
    exit 1
}
trap 'rm -rf -- "$tmpdir"' TERM INT EXIT HUP
export tmpdir

find '.' -mindepth 1 -maxdepth 1 \( -type f -o -type l \) -printf "%P\0" \
    | xargs -r0 -n 1 -P "$MAXPROCS" sh -c '
        set -e

        file="$1"
        realpath="$(realpath -- "$file")"

        case "$(file -b --mime-type -- "$realpath")" in
            video/*) :;;
            *) exit 0;;
        esac
        
        hash="$({ stat --printf "%F%i%n%s%W%Y" -- "$realpath"; printf "%s" "$SIZE" "$EXT"; } | sha512sum | cut -d" " -f1)"
        thumbfl="$CACHEDIR/$hash.$EXT"
        [ -s "$thumbfl" ] || ffmpegthumbnailer -i "$file" -o "$thumbfl" -m -s "$SIZE" 2> /dev/null
        cp -- "$thumbfl" "$tmpdir/$file.$EXT"
    ' --

{ "$NSXIV_EXEC" -0otp "$@" -- "$tmpdir"; rm -rf -- "${tmpdir:?}" > /dev/null; } \
    | sed -z "s|\.$EXT$||;s|^.*/||" \
    | sort -z \
    | eval "xargs -r0 -I FILE $OPENER ./FILE"
