#!/usr/bin/env sh

! command -v mktemp > /dev/null 2>&1 \
    || ! tmpdir="$(mktemp -d)" \
    || [ -z "$tmpdir" ] \
    && {
        tmpdir="${TMPDIR:-/tmp}/nsxiv_$$"
        mkdir -p -- "$tmpdir"
    }
trap 'rm -rf -- "$tmpdir"' TERM INT EXIT

find '.' \( -type f -o -type l \) -print \
    | sed 's|^\./||' \
    | grep -v '/' \
    | xargs file -L --mime-type -- \
    | grep ': image/.*$' \
    | sed 's|: image/.*$||' \
    | sort \
    | xargs -I FILE ffmpegthumbnailer -i FILE -o "$tmpdir/FILE.jpg" -m -s 384

{ nsxiv -ot -- "$tmpdir"; rm -rf -- "${tmpdir:?}" > /dev/null; } \
    | sed 's|.jpg$||;s|^.*/||' \
    | xargs -I FILE xdg-open ./FILE
