#!/usr/bin/env sh

tmpdir="$(mktemp -d)"

find '.' -mindepth 1 -maxdepth 1 \( -type f -o -type l \) -printf "%P\0" \
    | xargs -r0 -n 20 -P 64 file -00 -L --mime-type -- \
    | xargs -r0 -n 2 sh -c '
            case "$2" in
                video/*) printf "%s\0" "$1";;
            esac
        ' -- \
    | sort -z \
    | xargs -r0 -I FILE ffmpegthumbnailer -i FILE -o "$tmpdir/FILE.jpg" -m -s 384

{ nsxiv -0ot -- "$tmpdir"; rm -rf -- "${tmpdir:?}" > /dev/null; } \
    | sed -z 's|.jpg$||;s|^.*/||' \
    | xargs -r0 -I FILE xdg-open ./FILE
