#!/usr/bin/env sh

! command -v mktemp > /dev/null 2>&1 \
    || ! tmpdir="$(mktemp -d)" \
    || [ -z "$tmpdir" ] \
    && {
        tmpdir="${TMPDIR:-/tmp}/nsxiv_$$"
        mkdir -p -- "$tmpdir"
    }
trap 'rm -rf -- "$tmpdir"' TERM INT EXIT

find '.' \( -type f -o -type l \) -print \
    | sed 's|^\./||' \
    | grep -v '/' \
    | while IFS= read -r file; do
        file -L --mime-type -- "$file"
    done \
    | grep ': video/.*$' \
    | sed 's|: video/.*$||' \
    | sort \
    | while IFS= read -r file; do
        ffmpegthumbnailer -i "$file" -o "$tmpdir/$file.jpg" -m -s 384
    done

{ nsxiv -otp -- "$tmpdir"; rm -rf -- "${tmpdir:?}" > /dev/null; } \
    | sed 's|.jpg$||;s|^.*/||' \
    | while IFS= read -r file; do
        xdg-open ./"$file"
    done
